### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by sigma67** [sunsettrack4/easyepg#1]
Thank you for this great tool! Just commenting here to let you know I found some small issues in your setup instructions. My environment is Ubuntu 16 (WSL).

First, I needed to change xml-twig-tool to xml-twig-tools and remove cpan, as apt did not recognize it. Installing the perl package is also somewhat redundant since there is a system installation on Ubuntu. 

The internet check failed every time for me - I just removed those lines in the script.

**Comment by sunsettrack4** [comment]
Thanks for testing my script!
The internet check will be treated as warning as of now. README updated :)
https://github.com/sunsettrack4/easyepg/commit/478ecbd3cace5f9a069af41d1297ab3209a6cecc
