### ISSUE TITLE
Radiotimes: Malformed JSON String

### ISSUE THREAD

**Issue by xi784** [sunsettrack4/easyepg#11]
========== EPG CREATION: WARNING/ERROR LOG ============

^
     ^
[ EPG ERROR ] XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS:
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at epg_json2xml.pl line 235.
radiotimes.xml:634: parser error : Opening and ending tag mismatch: programme line 632 and tv
radiotimes.xml:635: parser error : Premature end of data in tag tv line 4
</tv>

=======================================================

[rdt_tmp.zip](https://github.com/sunsettrack4/easyepg/files/3379795/rdt_tmp.zip)

Dont know how it´s usefull.

Best regards.

**Comment by sunsettrack4** [comment]
Fixed: 2894dc644789907bd03d718599ff28687a996287
