### ISSUE TITLE
Feature request: Add HD-Plus as SAT-Provider DE/AT

### ISSUE THREAD

**Issue by xi784** [sunsettrack4/easyepg#12]
https://www.hd-plus.de/epg

This will add some special DE/AT SAT channels:
UHD1, travel4xp, Eurosport2 Xtra and some more.

greetz
dominik

**Comment by sunsettrack4** [comment]
Unfortunately, it's not possible to add this provider. It seems that the HD+ API requires a HMAC-SHA1 signature for every request. Due to the lack of API documentation and missing source code, there's no reliable way to collect the EPG data.
