### ISSUE TITLE
Basic XML escaping is missing

### ISSUE THREAD

**Issue by RayBa82** [sunsettrack4/easyepg#16]
TV Spielfilm fails because of missing XML escaping. Its probably missing for all other grabbers too.

At the moment a programme element contains `<us>` in the actor field and the grabber fails.

I fixed it for me with a small function in epg_json2xml.pl

`sub escape {
    # passing argument
    my $text = $_[0];
    $text =~ s/\&/&amp;/g;
    $text =~ s/\</\&lt;/g;
    $text =~ s/\>/\&gt;/g;
    return $text;
}`

**Comment by DeBaschdi** [comment]
Thx
fixed in https://github.com/sunsettrack4/easyepg/commit/50b0ad30effeff935a0913decf0d365194c400ac

please reopen, if this error still exist.
