### ISSUE TITLE
[ FATAL ERROR ] Required applications are missing

### ISSUE THREAD

**Issue by lordnikkon1983** [sunsettrack4/easyepg#25]
after the update to 0.4.3 came this message:

`Initializing script environment...
DateTime::Format::Strptime module for perl is requried but not installed!

[ FATAL ERROR ] Required applications are missing - Stop.
`

what can I do to make it work again? 

Greetz

**Comment by sunsettrack4** [comment]
sudo cpan install DateTime::Format::Strptime
