### ISSUE TITLE
docker failure

### ISSUE THREAD

**Issue by halfagascan** [sunsettrack4/easyepg#29]
Linux pc 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
https://hub.docker.com/r/mod242/easyepg
docker create \
  --name=easyepg \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Mexico_City \
  -v /home/me/easyepg:/easyepg \
  --log-opt max-size=50m \
  --restart unless-stopped \
  mod242/easyepg

The error:
 ----------------------------------------------
 EASYEPG SIMPLE XMLTV GRABBER                  
 Release v0.4.3 BETA                           
 powered by                                    
                                               
 ==THE=======================================  
   ##### ##### ##### #   # ##### ##### #####   
   #     #   # #     #   # #     #   # #       
  ##### ##### ##### #####  ##### ##### #  ##   
  #     #   #     #   #    #     #     #   #   
 ##### #   # #####   #     ##### #     #####   
 ===================================PROJECT==  
                                               
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4      
 ----------------------------------------------

Initializing script environment...
PhantomJS is required but it's not installed!
jq is required but it's not installed!
php is required but it's not installed!
xml-twig-tools is required but it's not installed!epg.sh: line 632: php: command not found

php-curl is required but it's not installed!
JSON module for perl is requried but not installed!
XML::Rules module for perl is requried but not installed!
XML::DOM module for perl is requried but not installed!
Data::Dumper module for perl is requried but not installed!
Time::Piece module for perl is requried but not installed!
Time::Seconds module for perl is requried but not installed!
uft8 module for perl is requried but not installed!
DateTime module for perl is requried but not installed!
DateTime::Format::DateParse module for perl is requried but not installed!
DateTime::Format::Strptime module for perl is requried but not installed!

[ FATAL ERROR ] Required applications are missing - Stop.

I am guessing you did not include the missing files for this docker

**Comment by DeBaschdi** [comment]
mod242's Docker is outdatet and broken, if u need to use Docker, please use 

https://hub.docker.com/r/qoopido/easyepg.minimal

**Comment by sunsettrack4** [comment]
This project page is not the correct place to report issues related to docker containers. Please go to: https://github.com/mod242/docker-easyepg  and report it there directly.
