### ISSUE TITLE
Zattoo EPG Grapper Error

### ISSUE THREAD

**Issue by Duell10111** [sunsettrack4/easyepg#31]
--------------------------------------------
 ZATTOO EPG SIMPLE XMLTV GRABBER
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4
 --------------------------------------------

+++ COUNTRY: SWITZERLAND +++

Login to Zattoo webservice... OK!

- DOWNLOAD PROCESS -

EPG details list not found, cache deleted!

Preparing database transmission...
0 broadcast files found!

Loading cached data files into new database...
DONE!

Preparing download...
1606 broadcast files to be downloaded!

Downloading EPG details...
Progress [####################] 100% DONE!

Downloading missing files... OK!

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!

========== EPG CREATION: WARNING/ERROR LOG ============

[ EPG ERROR ] XMLTV FILE DOES NOT CONTAIN ANY PROGRAMME DATA!
Not a HASH reference at epg_json2xml.pl line 133.

=======================================================

**Comment by sunsettrack4** [comment]
Please provide your settings / channel configurarion to reproduce the error.

**Comment by Duell10111** [comment]
Settings : 

`{ "settings": {
"day": "7",
"cid": "disabled",
"genre": "enabled",
"category": "enabled",
"episode": "xmltv_ns",
"settings": "true" }
}`

Channels :

`{"channels":["6+ HD","Rai 4","Rai 5","Rai Due HD","Rai Gulp","Rai Movie","RAI News","Rai Premium","Rai Scuola","Rai Sport","Rai Sport + HD"]}`

**Comment by ProGunShooter** [comment]
Same Problem here, 3 days ago everything work fine

+++ COUNTRY: GERMANY +++

Login to Zattoo webservice... OK!

- DOWNLOAD PROCESS -

Checking EPG details for updates...            
0 broadcast files to be updated!

Removing outdated EPG files...        
DONE!

Preparing database transmission...             
17025 broadcast files found!

Loading cached data files into new database...
Progress [####################] 100% DONE!

Preparing download...                              
0 broadcast files to be downloaded!

Downloading EPG details...                 
DONE!

Downloading missing files... OK!                            

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!                   

========== EPG CREATION: WARNING/ERROR LOG ============

[ EPG ERROR ] XMLTV FILE DOES NOT CONTAIN ANY PROGRAMME DATA!
Not a HASH reference at epg_json2xml.pl line 133.

**Comment by sunsettrack4** [comment]
Reference: https://www.kodinerds.net/index.php/Thread/55690-Aus-ZattooBoxExtBeta-wird-ZattooHiQ/?postID=574915#post574915

I'll fix it asap after my work.

**Comment by ProGunShooter** [comment]
Thanks a lot.
Best Regards

**Comment by sunsettrack4** [comment]
The error was caused by a change in the EPG JSON file. This change was undone by the provider, so you should be able to create Zattoo XML files again - after deleting the cache and reloading the data.

**Comment by ProGunShooter** [comment]
Works fine again, thanks
