### ISSUE TITLE
non-HD and HD channels

### ISSUE THREAD

**Issue by alfureu** [sunsettrack4/easyepg#33]
I was finally able to generate an xml list with your scripts, many thanks for them. Now I am facing the situation, where my IPTV provider lists a non-HD and HD version of the very same channel. The HD version of the channel is in your list. How can I copy/edit the scripts in order to have the same info for the non-HD channel as well?

**Comment by sunsettrack4** [comment]
Just choose the EPG ID of the channel and assign it to both channel types. You can do it in the M3U or in your tvHeadend configuration.
