### ISSUE TITLE
Issue with TVPLAYER[UK]

### ISSUE THREAD

**Issue by alfureu** [sunsettrack4/easyepg#34]
There is an error creating the json file with this source, I think I noticed for a moment an issue on line 47 maybe?

**Comment by sunsettrack4** [comment]
Fixed: https://github.com/sunsettrack4/easyepg/commit/e64161d783f943f084de938423436cf6e262e829

Please note that your IP address must belong to the UK to grab the EPG data.

**Comment by alfureu** [comment]
I see, thanks for clarifying. For those, who are looking for EPGs of channels like BBC etc, I found a solution in getting these from the Radiotimes grabber.
