### ISSUE TITLE
Install script does not work on Synology NAS

### ISSUE THREAD

**Issue by kekukui** [sunsettrack4/easyepg#37]
"**apt-get**" is not supported on Synology Linux.  If you build an installable Synology package with `spksrc`, they will host it here:

https://synocommunity.com
https://synocommunity.com/packages

https://github.com/SynoCommunity/spksrc

**Comment by DeBaschdi** [comment]
We can't implement apt-get on synology, sorry.

**Comment by sunsettrack4** [comment]
Please take a look at the installation instructions for Synology:
https://www.kodinerds.net/index.php/Thread/66690-Easy-EPG-auf-Synology-NAS-mittels-Docker-installieren/

**Comment by kekukui** [comment]
apt-get is **not** required if you build the package with `spksrc`.  (My Synology NAS does not support **Docker** - ARMv5 CPU)
