### ISSUE TITLE
Service provider unavailable! while adding vodafone

### ISSUE THREAD

**Issue by poFaber** [sunsettrack4/easyepg#44]
while on a move i switched from sat to cable and tried to add vodafone to the grabber instance.
started with a new and fresh install from github. 
want to add vodafone as provider. After "Fetching channel List" the is error message "Service provider unavailable! ". 
tried with both branches, original and debaschdi. Error is the same.
Please advise. Thanks!

**Comment by sunsettrack4** [comment]
Vodafone decided to close down the TV Manager services. Therefore, this provider is unavailable.

https://tv-manager.vodafone.de/tv-manager/
