### ISSUE TITLE
Zattoo [ LOGIN ERROR ]

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [sunsettrack4/easyepg#46]
Error says
`[ LOGIN ERROR ] Please check your credentials!`
since a few days.

**Comment by sunsettrack4** [comment]
Error fixed 4 days ago, please update the script and try again.

https://github.com/sunsettrack4/easyepg/commit/104498ce5483d2bb53d21f6ae376b063e1cff0a8

**Comment by Unkn0wn-MDCLXIV** [comment]
I updated my local repo, but I had to run the update from the main menu.
Now it's working flawlessly again.
