### ISSUE TITLE
[HORIZON] Duplicated Channel IDs error

### ISSUE THREAD

**Issue by CSchlipp** [sunsettrack4/easyepg#50]
I stumbled upon easyepg a while ago and wanted to try it out today.

Unfortunately, I cannot get the most recent version producing an xml-file in the qoopido/easyepg.minimal docker image. 
The Horizon Grabber throws the following error:

```
 --------------------------------------------
 HORIZON EPG SIMPLE XMLTV GRABBER
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4
 --------------------------------------------

+++ COUNTRY: GERMANY +++

- DOWNLOAD PROCESS -

Checking manifest files...
1 manifest file(s) to be downloaded!

Loading manifest files...
DONE!

Creating EPG manifest file... DONE!

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!

========== EPG CREATION: WARNING/ERROR LOG ============

[ DUPLICATE ] <channel id="Fox HD">
[ EPG ERROR ] XMLTV FILE CONTAINS DUPLICATED CHANNEL IDs!

=======================================================

```

In this case, I've only selected "Fox HD", but some other channels seems to trigger the same error as well (e.g. NatGeo HD, SYFY HD, TNT Comedy, ...)

It doesn't make a difference if Rytec IDs are enabled or not. If enabled, the error changes to
```
...
[ DUPLICATE ] <channel id="Fox.de">
...
```

Finally, no xml file gets created.

**Comment by tinect** [comment]
Same here without docker

**Comment by CSchlipp** [comment]
The "TESTING" branch is quite a bit behind the master branch, but works.

**Comment by sunsettrack4** [comment]
I just added the fixes to the main branch: https://github.com/sunsettrack4/easyepg/commit/2e1fec9a987a465960cd43fe34c8a349b3404518

Please update the script and retry to set up the channels for Horizon.

**Comment by CSchlipp** [comment]
Thanks!
Changed the branch in my Docker container yesterday, but kept the configuration files. Everything's working so far!
