### ISSUE TITLE
 XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS

### ISSUE THREAD

**Issue by MidavSec** [sunsettrack4/easyepg#51]
[ EPG ERROR ] XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS:
horizon.xml:640923: parser error : Opening and ending tag mismatch: channel line 364 and tv
horizon.xml:640924: parser error : Premature end of data in tag tv line 4
</tv>

Thanks for the great project, how can I fix this error?

**Comment by sunsettrack4** [comment]
Please provide the XML file (horizon.xml), so I can check what went wrong there.

**Comment by MidavSec** [comment]
> Great thanks, found only this file:

root@debian-test:~/easyepg-new# find ./ -iname *.xml*
./hzn/de/horizon_ERROR.xml

https://gofile.io/d/7M7UCu

Thank you very much!

**Comment by MidavSec** [comment]
Found a work-around:

Remove this channels from the menu selection list:

Sat.1 emotions HD
Eurosport360 HD 9

to bypass the initial errors. Then I had to remove:

[ DUPLICATE ] channel id="13th Street HD">"
[ DUPLICATE ] channel id="Boomerang">"
[ DUPLICATE ] channel id="Discovery HD">"
[ DUPLICATE ] channel id="Fox HD">"
[ DUPLICATE ] channel id="NatGeo HD">"
[ DUPLICATE ] channel id="National Geographic Wild HD">"
[ DUPLICATE ] channel id="Nick.Jr.">"
[ DUPLICATE ] channel id="Romance TV">"
[ DUPLICATE ] channel id="SYFY HD">"
[ DUPLICATE ] channel id="TNT Comedy">"
[ DUPLICATE ] channel id="TNT Film">"
[ DUPLICATE ] channel id="TNT Serie HD">"

Now I have the issue that no EPG is shown for duplicated channels (because I removed them from menu to generate the xml). Is there a way to include them? Initially I selected all channels (to reproduce it).

Thanks.

**Comment by sunsettrack4** [comment]
I fixed the error mentioned in your first post: https://github.com/sunsettrack4/easyepg/commit/cb84edc353422c3fcd565ee2b38751539664fc47

Please note that the provider uses duplicated IDs for some channels causing the [DUPLICATE] error in easyEPG.
However, in a new version of my script, this error will be fixed as well.
