### ISSUE TITLE
error getting epg from telekom

### ISSUE THREAD

**Issue by tinect** [sunsettrack4/easyepg#54]
Just tested with the first channel in channel list.
![image](https://user-images.githubusercontent.com/135993/104852347-e27f6480-58fa-11eb-9d50-9dd94e2833d1.png)

Aborting this endless query, I've to remove the grabber instance because you cannot edit the channel list any more.

Anyone has an idea?

**Comment by sunsettrack4** [comment]
Fixed: 9a669762684d954f9d803899ba2d1560f474a7fd

Please note that a new setup of the provider is required to retrieve the EPG data again.
