### ISSUE TITLE
Can not Log-In to Waipu.tv Channel List

### ISSUE THREAD

**Issue by githubJond** [sunsettrack4/easyepg#56]
Can not Log-In to Waipu.tv Channel List.
Credentials working on website.

Thanks for this amazing Build!

**Comment by sunsettrack4** [comment]
Cannot reproduce your problem. 
Log file is required here.

Thanks for using my script! :)

**Comment by AnneWielis** [comment]
I have the same problem with zattoo. Where can i find the log file?

**Comment by sunsettrack4** [comment]
No log files provided - issue closed.
