### ISSUE TITLE
XML file validation failed

### ISSUE THREAD

**Issue by mrrepel** [sunsettrack4/easyepg#57]
Hi,

After installing easyepg i get the following error:

HORIZON EPG SIMPLE XMLTV GRABBER
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4
 --------------------------------------------

+++ COUNTRY: NETHERLANDS +++

- DOWNLOAD PROCESS -

Checking manifest files...
71 manifest file(s) to be downloaded!

Loading manifest files...
DONE!

Creating EPG manifest file... DONE!

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!

========== EPG CREATION: WARNING/ERROR LOG ============

                                ^
  <category lang="nl">Business & Financial</category>
[ EPG ERROR ] XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS:
horizon.xml:12822: parser error : xmlParseEntityRef: no name
horizon.xml:31772: parser error : xmlParseEntityRef: no name
horizon.xml:49098: parser error : xmlParseEntityRef: no name
horizon.xml:49106: parser error : xmlParseEntityRef: no name
horizon.xml:49271: parser error : xmlParseEntityRef: no name
horizon.xml:49865: parser error : xmlParseEntityRef: no name
horizon.xml:50055: parser error : xmlParseEntityRef: no name
horizon.xml:50332: parser error : xmlParseEntityRef: no name
horizon.xml:50341: parser error : xmlParseEntityRef: no name
horizon.xml:50364: parser error : xmlParseEntityRef: no name
horizon.xml:50372: parser error : xmlParseEntityRef: no name
horizon.xml:50387: parser error : xmlParseEntityRef: no name
horizon.xml:50394: parser error : xmlParseEntityRef: no name
horizon.xml:50401: parser error : xmlParseEntityRef: no name
horizon.xml:50408: parser error : xmlParseEntityRef: no name
horizon.xml:50415: parser error : xmlParseEntityRef: no name
horizon.xml:50422: parser error : xmlParseEntityRef: no name
horizon.xml:50429: parser error : xmlParseEntityRef: no name
horizon.xml:50436: parser error : xmlParseEntityRef: no name
horizon.xml:50443: parser error : xmlParseEntityRef: no name
horizon.xml:50450: parser error : xmlParseEntityRef: no name
horizon.xml:50458: parser error : xmlParseEntityRef: no name
horizon.xml:50467: parser error : xmlParseEntityRef: no name
horizon.xml:50490: parser error : xmlParseEntityRef: no name
horizon.xml:50498: parser error : xmlParseEntityRef: no name
horizon.xml:50513: parser error : xmlParseEntityRef: no name
horizon.xml:50520: parser error : xmlParseEntityRef: no name
horizon.xml:50527: parser error : xmlParseEntityRef: no name
horizon.xml:50534: parser error : xmlParseEntityRef: no name
horizon.xml:50541: parser error : xmlParseEntityRef: no name
horizon.xml:50548: parser error : xmlParseEntityRef: no name
horizon.xml:50555: parser error : xmlParseEntityRef: no name
horizon.xml:50563: parser error : xmlParseEntityRef: no name
horizon.xml:50570: parser error : xmlParseEntityRef: no name
horizon.xml:50577: parser error : xmlParseEntityRef: no name
horizon.xml:8946: parser error : xmlParseEntityRef: no name
horizon.xml:8955: parser error : xmlParseEntityRef: no name
horizon.xml:8964: parser error : xmlParseEntityRef: no name
horizon.xml:8973: parser error : xmlParseEntityRef: no name
horizon.xml:8982: parser error : xmlParseEntityRef: no name
horizon.xml:8991: parser error : xmlParseEntityRef: no name
horizon.xml:9000: parser error : xmlParseEntityRef: no name
horizon.xml:9113: parser error : xmlParseEntityRef: no name
horizon.xml:9306: parser error : xmlParseEntityRef: no name
horizon.xml:9324: parser error : xmlParseEntityRef: no name
horizon.xml:9598: parser error : xmlParseEntityRef: no name
horizon.xml:9607: parser error : xmlParseEntityRef: no name
horizon.xml:9616: parser error : xmlParseEntityRef: no name
horizon.xml:9625: parser error : xmlParseEntityRef: no name
horizon.xml:9634: parser error : xmlParseEntityRef: no name
horizon.xml:9643: parser error : xmlParseEntityRef: no name
horizon.xml:9652: parser error : xmlParseEntityRef: no name
horizon.xml:9661: parser error : xmlParseEntityRef: no name
horizon.xml:9710: parser error : xmlParseEntityRef: no name
horizon.xml:9947: parser error : xmlParseEntityRef: no name

=======================================================

**Comment by sunsettrack4** [comment]
https://github.com/sunsettrack4/easyepg/issues/60

**Comment by sunsettrack4** [comment]
Fixed
