### ISSUE TITLE
Service provider unavailable

### ISSUE THREAD

**Issue by nikdom** [sunsettrack4/easyepg#58]
```
+++ COUNTRY: GERMANY +++

Service provider unavailable!
```

Getting this if i want to grab zattoo germany. when trying to add a new gabber instance with zattoo DE, Germany is not selectable, but only Switzerland. Is support for Zattoo Germany discontinued?

**Comment by nikdom** [comment]
updated to latest master did not work in the first place, updating it via the script menu, it works. my bad.

**Comment by sunsettrack4** [comment]
Just update the script to solve this problem (main menu, option 5). And you cannot add the provider setup if the same provider has been added in the past, so you have to open the grabber settings to manage the instance.
