### ISSUE TITLE
Horizon PL  EPG grabber error

### ISSUE THREAD

**Issue by paulh384** [sunsettrack4/easyepg#59]
I get this error consistently while setting up the grabber and running it.

 --------------------------------------------
 HORIZON EPG SIMPLE XMLTV GRABBER
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4
 --------------------------------------------

+++ COUNTRY: POLAND +++

- DOWNLOAD PROCESS -

Checking manifest files...
0 manifest file(s) to be downloaded!

Loading manifest files...
DONE!

Creating EPG manifest file... cat: 'mani/*': No such file or directory
DONE!

================= CHANNEL LIST: LOG ===================

unexpected end of string while parsing JSON string, at character offset 48014 (before "ttps://wp23-images-p...") at url_printer.pl line 56.

=======================================================

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!

========== EPG CREATION: WARNING/ERROR LOG ============

^
[ EPG ERROR ] XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS:
horizon.xml:1: parser error : Document is empty
unexpected end of string while parsing JSON string, at character offset 48014 (before "ttps://wp23-images-p...") at ch_json2xml.pl line 75.
unexpected end of string while parsing JSON string, at character offset 48014 (before "ttps://wp23-images-p...") at epg_json2xml.pl line 96.

=======================================================

Press any key to continue...

**Comment by sunsettrack4** [comment]
Fixed: https://github.com/sunsettrack4/easyepg/commit/fe142671d87df6a1cd1813d691f406ba4449c6aa

Please use the update feature of my script to fix the issue.

Thanks for your report :+1:
