### ISSUE TITLE
Persistent Config

### ISSUE THREAD

**Issue by demenzio** [sunsettrack4/easyepg#6]
Hey I am creating a docker containter and I was wondering: 

Where are the settings (e.g. after creating a grabber instance with selected channels) saved at ?
Could not find any. Maybe I just missed it.

I'd like to make them persistent via volume mount. 

Thanks.

**Comment by sunsettrack4** [comment]
Example for Magenta TV DE: tkm/de/channels.json
Example for combined XML called "test" with Magenta TV DE: combine/test/tkm_de_channels.json

**Comment by demenzio** [comment]
Great thanks!
