### ISSUE TITLE
OLDPWD not set 

### ISSUE THREAD

**Issue by picanl** [sunsettrack4/easyepg#7]
Debian 8 

settings.sh: line 494: cd: OLDPWD not set
settings.sh: line 507: cd: OLDPWD not set

xml wil not be created.

**Comment by sunsettrack4** [comment]
Please add the following line at the beginning of epg.sh script:

cd $(pwd)

Does this command solve your problem?
Please note that pwd must be installed on your system.

**Comment by sunsettrack4** [comment]
Fix included: e62f66e840ba01dc070175c7f0ffa93f8247f6fe
If the error still exists, please reopen this issue or create a new one.
