### ISSUE TITLE
hzn cz not working

### ISSUE THREAD

**Issue by FrAcTi0N** [sunsettrack4/easyepg#73]
horizon for cz is not working anymore past days, here is the output:
`HORIZON EPG SIMPLE XMLTV GRABBER            
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4    
 --------------------------------------------

+++ COUNTRY: CZECH REPUBLIC +++
Service provider unavailable!`

also i was looking into the settings and it seems, that there is something bad on hzn api. Here is another output:

`pi@rpi4:~ $ wget https://web-api-pepper.horizon.tv/oesp/v2/CZ/ces/web/programschedules/20220210/1
--2022-02-06 19:25:01--  https://web-api-pepper.horizon.tv/oesp/v2/CZ/ces/web/programschedules/20220210/1
Resolving web-api-pepper.horizon.tv (web-api-pepper.horizon.tv)... 104.96.155.207, 2a02:26f0:4700:29d::437f, 2a02:26f0:4700:287::437f
Connecting to web-api-pepper.horizon.tv (web-api-pepper.horizon.tv)|104.96.155.207|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-06 19:25:11 ERROR 404: Not Found.`

Thank You

**Comment by master-magic** [comment]
CZ is not annymore in horizon package, 
Its been removed.

**Comment by FrAcTi0N** [comment]
Thanx for info. I was afraid of this... Would be great, if anyone can add https://www.fdb.cz/tv/ ...

**Comment by sunsettrack4** [comment]
Fixed: https://github.com/sunsettrack4/easyepg/commit/774ae71244b5564d841df76427c2a0efd900201b
