### ISSUE TITLE
EPG process fails for TKM

### ISSUE THREAD

**Issue by Multifluid** [sunsettrack4/easyepg#74]
The error message is

Bytes: 0xE4 0x72 0x20 0x31

[ EPG ERROR ] XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS:
magenta.xml:3: parser error : Input is not proper UTF-8, indicate encoding !

This seems to happen since a couple of days, looks like my last working xml file is from Feb 28th which makes me wonder if there were changes at March 1st.

**Comment by Multifluid** [comment]
Just checked, it is just the validation that fails. The xml file is generated and when I import it to my TVMosaik server ist works. I doesn't look any different than the old file.

**Comment by peddyhh** [comment]
Maybe I found the problem.
I suppose, you are using an encoding with german "umlauten".
Please try in shell:
`date`

Maybe you can see the problem:
`Fr 18. M�r 19:56:19 CET 2022`

Try
`date -R`
the resuld should be
`Fri, 18 Mar 2022 19:57:56 +0100`

**A Quick-Fix:**
Replace
`sed -i "s/<tv>/<\!-- created on $(date) -->\n&\n\n<!-- CHANNEL LIST -->\n/g" external`
with
`sed -i "s/<tv>/<\!-- created on $(date -R) -->\n&\n\n<!-- CHANNEL LIST -->\n/g" external`
in all used shellscripts.

**Comment by Multifluid** [comment]
Cool, thx. I'll check and let you know.

And yes, I'm using German.

**Comment by Multifluid** [comment]
Yes, that solved it for me. 

Thanks a lot!
