### ISSUE TITLE
horizon DE

### ISSUE THREAD

**Issue by jimmybonesde** [sunsettrack4/easyepg#79]
Hi there
Horizon DE brroken since yesterday

+++ COUNTRY: GERMANY +++

- DOWNLOAD PROCESS -

Checking manifest files...
334 manifest file(s) to be downloaded!

Loading manifest files...
Progress [################### ]  95% DONE!

Creating EPG manifest file... DONE!

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!

========== EPG CREATION: WARNING/ERROR LOG ============

[ EPG ERROR ] XMLTV FILE DOES NOT CONTAIN ANY PROGRAMME DATA!

=======================================================

**Comment by sunsettrack4** [comment]
It's not broken, Horizon doesn't provide any data.
https://www.horizon.tv/de_de/tv/tv-programm.html
